import os
import sys

# -- Project information -----------------------------------------------------
project = 'MIR'
copyright = '2025, Vladimir Makarov'
author = 'Vladimir Makarov'
release = '0.2'

# -- General configuration ---------------------------------------------------
extensions = [
    'breathe',
    'sphinx_rtd_theme',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Breathe Configuration ---------------------------------------------------
# This connects Sphinx to the XML output generated by Doxygen
breathe_projects = {
    "MIR": "_build/xml" 
}
breathe_default_project = "MIR"

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

# -- Options for LaTeX/PDF output ---------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',

    # Literal blocks (code) often overflow margins in PDFs. 
    # This snippet creates a smaller font environment for code blocks.
    'preamble': r'''
        \usepackage{inconsolata}
        \fvset{fontsize=\small}
        \RecustomVerbatimEnvironment{Verbatim}{Verbatim}{fontsize=\small}
    ''',
}

# Grouping the document tree into LaTeX files. List of tuples:
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('index', 'MIR_Technical_Manual.tex', 'The Anatomy of a C JIT',
     'Vladimir Makarov', 'manual'),
]

# -- Fix for C/C++ confusion -------------------------------------------------
# Force Breathe to interpret all files as C domain, preventing namespace errors.
breathe_domain_by_extension = {
    "h" : "c",
    "c" : "c",
}
